### ISSUE TITLE
Feature Request: Add external source for quotes

### ISSUE THREAD

**Issue by sirpooya** [ayltai/Developers-Excuses#11]
Hey man 👋
I came across this ScreenSaver and I need it so bad, bus since I am a "Designer", developer quotes has no good for me.
I was wondering if it's possible to tweak the code to read quotes from an external source (like a JSON API) so that users can change the quotes themselves.

Peace Out ✌️

**Comment by ayltai** [comment]
What sources do you have in mind?

If you don't mind working a little bit with Xcode, you can change the hardcoded quotes in the project and hit Command+B to build it, then right-click the new screensaver to install it.

**Comment by sirpooya** [comment]
I have a list of quotes in Google Sheet which I can convert to JSON API, but the problem is that I  need the swift code that reads the API from a hardcoded address & parses it into an array.

**Comment by ayltai** [comment]
Yeah I mean, if you could provide the address of some websites that provide any kinds of API to retrieve quotes, I can probably integrate them to the screensaver.

**Comment by sirpooya** [comment]
This website randomly generates quotes about Design: https://quotesondesign.com
and I also have my own customized version of quotes in this address:
https://api.npoint.io/8945641a06073f78741b

**Comment by sirpooya** [comment]
Hey @ayltai any news yet?

**Comment by ayltai** [comment]
Yep I'm going to add it (after my long vacation until next week 😄 )

**Comment by ayltai** [comment]
New version v1.5 released. Instead of reading quotes from external sources (e.g. websites and APIs), I've made quotes customizable in the screen saver configuration screen. Check out README.md for the screenshot.
