### ISSUE TITLE
Unsplash photos not working on Big Sur 11.2.3

### ISSUE THREAD

**Issue by lesliecdubs** [ayltai/Developers-Excuses#14]
**Describe the bug**
Screensaver in Big Sur 11.2.3 won't work with Unsplash photos enabled.

If photo setting is on, screensaver is a black screen with no images or text.
If photo setting is disabled, screener shows excuses updating as expected on black background.

I've tried downloading directly and also [building myself](https://github.com/ayltai/MacOS-Developers-Excuses#how-to-build). I love this screensaver so much, hoping to get it running again 🙏🏻 

**To Reproduce**
Install or build locally on Big Sur and try to run it

**Comment by ayltai** [comment]
Glad to know someone likes it! I reproduced this issue on Catalina, fixed an outdated Unsplash API response, and now it works on my machine. Unfortunately, I am not unable to test it on Big Sur until I am allowed to upgrade my company-owned laptop.

Please try [release/1.7](https://github.com/ayltai/MacOS-Developers-Excuses/releases/download/release%2F1.7/screensaver.zip) to see if it works on Big Sur.

**Comment by lesliecdubs** [comment]
That release works on Big Sur 🎉 This screensaver is back in action my machine.

Thanks for fixing that outdated Unsplash API response!
