### ISSUE TITLE
Dosn’t run on Sonoma (Mac OS 14.2.1)

### ISSUE THREAD

**Issue by mischah** [ayltai/Developers-Excuses#16]
**Describe the bug**
Instead of starting the screensaver I only see a black screen. 

After unlocking the screen ist shows the following error message:

> "Developers Excuses.saver" cannot be opened because Apple cannot search for malware in it.
> This software needs to be updated.
> Contact the developer for more information.

**To Reproduce**
1. Install the Screensaver on Mac OS 14.2.1
2. Select the Develpoper Excuses Screensaver in the Screensaver Pref Pane.
  a. Click on »Preview« in the Screensaver Pref Pane 
  b. or Activate the Screensaver (eg. via active corner)
3. Move the mouse the leave the screensaver
5. See error

**Expected behavior**
Showing Developer Excuses 🤓 

**Screenshots**

![image](https://github.com/ayltai/MacOS-Developers-Excuses/assets/441011/19a12bb6-86c9-4506-86dc-dfdc146b540a)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.2.1

**Additional context**
Guess that’s it.

**Comment by ayltai** [comment]
Thanks for reporting. As this screensaver is not signed by Apple (by paying a fortune), macOS threatened users with that error message.
As a workaround, you could build the project in Xcode on your mac, which will self-sign the screensaver and prevent the error message from appearing.

**Comment by mischah** [comment]
Thanks. So this is not a new thing I guess.

Can’t remember that I’ve build this for my old machine. 

But then im going to build it via Xcode :shipit:
