### ISSUE TITLE
Not working in macOS Mojave

### ISSUE THREAD

**Issue by mediter** [ayltai/Developers-Excuses#2]
![2018-09-12 11 45 18](https://user-images.githubusercontent.com/57368/45401082-93b5c600-b681-11e8-9b5e-127e860cafdd.jpg)

**Comment by ayltai** [comment]
Thanks for letting me know. I will take a look when my mac gets the update.

**Comment by nicmilot** [comment]
+1

**Comment by tracure1337** [comment]
+1

**Comment by ayltai** [comment]
I have no idea why it doesn't work on Mojave. I tried to build an empty screensaver project using Swift 4 in Xcode 10.1, and got the same result.

**Comment by azarakovskiy** [comment]
@ayltai found a similar thread, maybe this comment would help https://github.com/JohnCoates/Aerial/issues/464#issuecomment-435626674

**Comment by ayltai** [comment]
@azarakovskiy It works! THANKS!!

**Comment by azarakovskiy** [comment]
@ayltai glad that it helped, I couldn't sleep without this screensaver :)
