### ISSUE TITLE
After updating to Catalina, text became very small and image is not shown

### ISSUE THREAD

**Issue by azarakovskiy** [ayltai/Developers-Excuses#5]
My Mac got an update. It's Catalina, fresh and shiny.

Unfortunately, the screensaver stopped working as expected.
First, update removed the Unsplash API key which led to 401s. Ok, that' easy to solve.

1. When ^^ is solved, I see that the screensaver loads images because the name and the link to an image are written in the corners. Sadly, the image is not shown -> completely black screen.

2. Also, ALL the text (incl. an excuse and links to an image) is now super small and it seems that it is impossible to change the default font (just nothing happens when I try in screensaver settings).
It doesn't seem though that the small text is related to font settings (I have 45pt which supposed to be quite enough).

**Comment by ayltai** [comment]
Thanks for reporting. I will have a look shortly.

**Comment by adroste** [comment]
@ayltai same problem here

**Comment by ayltai** [comment]
Fixed in https://github.com/ayltai/MacOS-Developers-Excuses/commit/c47c21f0083423901e91f70d47bdb3c4e5e70a57
