### ISSUE TITLE
macOS 10.15.4 repeatedly blocks app due to verification issues (potential malware warning)

### ISSUE THREAD

**Issue by spkane** [ayltai/Developers-Excuses#9]
**Describe the bug**
The newest macOS Catalina builds (10.15.4) will run this screensaver, but require me to authorize it on almost a daily basis, because the OS complains that it can not determine wether the application might have malware. I'm assuming that this is something to do with Apple Notarization missing from the screensaver. I don't have the exact message at the moment, but I'll try and add it when I see it again in the next day or so.

**To Reproduce**
Try to run the screensaver (roughly a day or more after the last time)

**Expected behavior**
It runs. At least after the first time I authorize it.

**Screenshots**
I'll add this the next time it happens.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.4

**Additional context**
N/A

**Comment by ayltai** [comment]
In that case, you have to build this project in Xcode yourself. This screensaver is distributed unsigned (because I don't want to pay Apple 99 USD per year).

**Comment by spkane** [comment]
It might be worth documenting that in the README, simply to make it easier to troubleshoot and remedy for users.

**Comment by spkane** [comment]
https://github.com/ayltai/MacOS-Developers-Excuses/pull/10

**Comment by ayltai** [comment]
Resolved in https://github.com/ayltai/MacOS-Developers-Excuses/pull/10
